<?php

namespace App\Filament\Resources\PersonerData\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class PersonerDataInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('personnamn')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('gatuadress')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('postnummer')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('postort')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_data_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('hitta_personnamn')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_gatuadress')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_postnummer')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_postort')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_alder')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_kon')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_telefon')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_karta')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_link')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_bostadstyp')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hitta_bostadspris')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('hitta_is_active')
                    ->boolean(),
                IconEntry::make('hitta_is_telefon')
                    ->boolean(),
                IconEntry::make('hitta_is_hus')
                    ->boolean(),
                TextEntry::make('hitta_created_at')
                    ->dateTime(),
                TextEntry::make('hitta_updated_at')
                    ->dateTime(),
                TextEntry::make('merinfo_data_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('merinfo_personnamn')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_alder')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_kon')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_gatuadress')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_postnummer')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_postort')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_karta')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_link')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_bostadstyp')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('merinfo_bostadspris')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('merinfo_is_active')
                    ->boolean(),
                IconEntry::make('merinfo_is_telefon')
                    ->boolean(),
                IconEntry::make('merinfo_is_hus')
                    ->boolean(),
                TextEntry::make('merinfo_created_at')
                    ->dateTime(),
                TextEntry::make('merinfo_updated_at')
                    ->dateTime(),
                TextEntry::make('ratsit_data_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ratsit_gatuadress')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_postnummer')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_postort')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_forsamling')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_kommun')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_lan')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_adressandring')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_kommun_ratsit')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_stjarntacken')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_fodelsedag')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_personnummer')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_alder')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_kon')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_civilstand')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_fornamn')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_efternamn')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_personnamn')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_agandeform')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_bostadstyp')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_boarea')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_byggar')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_fastighet')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_longitude')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_latitud')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_google_maps')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_google_streetview')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ratsit_ratsit_se')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('ratsit_is_active')
                    ->boolean(),
                IconEntry::make('ratsit_is_telefon')
                    ->boolean(),
                IconEntry::make('ratsit_is_hus')
                    ->boolean(),
                TextEntry::make('ratsit_created_at')
                    ->dateTime(),
                TextEntry::make('ratsit_updated_at')
                    ->dateTime(),
                IconEntry::make('is_active')
                    ->boolean(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
