<?php

namespace App\Filament\Resources\PersonerData\Schemas;

use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class PersonerDataForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Textarea::make('personnamn')
                    ->columnSpanFull(),
                Textarea::make('gatuadress')
                    ->columnSpanFull(),
                Textarea::make('postnummer')
                    ->columnSpanFull(),
                Textarea::make('postort')
                    ->columnSpanFull(),
                TextInput::make('hitta_data_id')
                    ->numeric(),
                Textarea::make('hitta_personnamn')
                    ->columnSpanFull(),
                Textarea::make('hitta_gatuadress')
                    ->columnSpanFull(),
                Textarea::make('hitta_postnummer')
                    ->columnSpanFull(),
                Textarea::make('hitta_postort')
                    ->columnSpanFull(),
                Textarea::make('hitta_alder')
                    ->columnSpanFull(),
                Textarea::make('hitta_kon')
                    ->columnSpanFull(),
                Textarea::make('hitta_telefon')
                    ->columnSpanFull(),
                Textarea::make('hitta_karta')
                    ->columnSpanFull(),
                Textarea::make('hitta_link')
                    ->columnSpanFull(),
                Textarea::make('hitta_bostadstyp')
                    ->columnSpanFull(),
                Textarea::make('hitta_bostadspris')
                    ->columnSpanFull(),
                Toggle::make('hitta_is_active')
                    ->required(),
                Toggle::make('hitta_is_telefon')
                    ->required(),
                Toggle::make('hitta_is_hus')
                    ->required(),
                DateTimePicker::make('hitta_created_at')
                    ->required(),
                DateTimePicker::make('hitta_updated_at')
                    ->required(),
                TextInput::make('merinfo_data_id')
                    ->numeric(),
                Textarea::make('merinfo_personnamn')
                    ->columnSpanFull(),
                Textarea::make('merinfo_alder')
                    ->columnSpanFull(),
                Textarea::make('merinfo_kon')
                    ->columnSpanFull(),
                Textarea::make('merinfo_gatuadress')
                    ->columnSpanFull(),
                Textarea::make('merinfo_postnummer')
                    ->columnSpanFull(),
                Textarea::make('merinfo_postort')
                    ->columnSpanFull(),
                TextInput::make('merinfo_telefon')
                    ->tel(),
                Textarea::make('merinfo_karta')
                    ->columnSpanFull(),
                Textarea::make('merinfo_link')
                    ->columnSpanFull(),
                Textarea::make('merinfo_bostadstyp')
                    ->columnSpanFull(),
                Textarea::make('merinfo_bostadspris')
                    ->columnSpanFull(),
                Toggle::make('merinfo_is_active')
                    ->required(),
                Toggle::make('merinfo_is_telefon')
                    ->required(),
                Toggle::make('merinfo_is_hus')
                    ->required(),
                DateTimePicker::make('merinfo_created_at')
                    ->required(),
                DateTimePicker::make('merinfo_updated_at')
                    ->required(),
                TextInput::make('ratsit_data_id')
                    ->numeric(),
                Textarea::make('ratsit_gatuadress')
                    ->columnSpanFull(),
                Textarea::make('ratsit_postnummer')
                    ->columnSpanFull(),
                Textarea::make('ratsit_postort')
                    ->columnSpanFull(),
                Textarea::make('ratsit_forsamling')
                    ->columnSpanFull(),
                Textarea::make('ratsit_kommun')
                    ->columnSpanFull(),
                Textarea::make('ratsit_lan')
                    ->columnSpanFull(),
                Textarea::make('ratsit_adressandring')
                    ->columnSpanFull(),
                Textarea::make('ratsit_kommun_ratsit')
                    ->columnSpanFull(),
                Textarea::make('ratsit_stjarntacken')
                    ->columnSpanFull(),
                Textarea::make('ratsit_fodelsedag')
                    ->columnSpanFull(),
                Textarea::make('ratsit_personnummer')
                    ->columnSpanFull(),
                Textarea::make('ratsit_alder')
                    ->columnSpanFull(),
                Textarea::make('ratsit_kon')
                    ->columnSpanFull(),
                Textarea::make('ratsit_civilstand')
                    ->columnSpanFull(),
                Textarea::make('ratsit_fornamn')
                    ->columnSpanFull(),
                Textarea::make('ratsit_efternamn')
                    ->columnSpanFull(),
                Textarea::make('ratsit_personnamn')
                    ->columnSpanFull(),
                Textarea::make('ratsit_agandeform')
                    ->columnSpanFull(),
                Textarea::make('ratsit_bostadstyp')
                    ->columnSpanFull(),
                Textarea::make('ratsit_boarea')
                    ->columnSpanFull(),
                Textarea::make('ratsit_byggar')
                    ->columnSpanFull(),
                Textarea::make('ratsit_fastighet')
                    ->columnSpanFull(),
                TextInput::make('ratsit_telfonnummer')
                    ->tel(),
                TextInput::make('ratsit_epost_adress'),
                TextInput::make('ratsit_personer'),
                TextInput::make('ratsit_foretag'),
                TextInput::make('ratsit_grannar'),
                TextInput::make('ratsit_fordon'),
                TextInput::make('ratsit_hundar'),
                TextInput::make('ratsit_bolagsengagemang'),
                Textarea::make('ratsit_longitude')
                    ->columnSpanFull(),
                Textarea::make('ratsit_latitud')
                    ->columnSpanFull(),
                Textarea::make('ratsit_google_maps')
                    ->columnSpanFull(),
                Textarea::make('ratsit_google_streetview')
                    ->columnSpanFull(),
                Textarea::make('ratsit_ratsit_se')
                    ->columnSpanFull(),
                Toggle::make('ratsit_is_active')
                    ->required(),
                Toggle::make('ratsit_is_telefon')
                    ->required(),
                Toggle::make('ratsit_is_hus')
                    ->required(),
                DateTimePicker::make('ratsit_created_at')
                    ->required(),
                DateTimePicker::make('ratsit_updated_at')
                    ->required(),
                Toggle::make('is_active')
                    ->required(),
            ]);
    }
}
